
<h4>Lab No 3</h4>
<h4 align="right">Utkarsh Bhangale<br>2020802124</h4>


Aim : To perform Preprocessing , Normalization and Standardization on the given dataset using
1. By creating functions.
2. By using sklearn library.
And validating the results

In [2]:
 # Importing Required libraries import pandas as pd 
import numpy as np
import pandas as pd

In [9]:
Url = "https://raw.githubusercontent.com/shrikant-temburwar/Loan-Prediction-Dataset/master/train.csv"
df = pd.read_csv(Url)
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [4]:
all_data_na = (df.isnull().sum() / len(df)) * 100 
all_data_na = all_data_na.drop(all_data_na[all_data_na == 0].index).sort_values()
missing_data =pd.DataFrame({'Missing Ratio (in %)':all_data_na}) 
missing_data.head(20)

Missing Ratio (in %)
Married                       0.488599
Gender                        2.117264
Loan_Amount_Term              2.280130
Dependents                    2.442997
LoanAmount                    3.583062
Self_Employed                 5.211726
Credit_History                8.143322

In [5]:
df = df['LoanAmount'].fillna(df['LoanAmount'].mean())

In [6]:
# Functions for Normalization
# min-max normalization function
def minmaxx(df):
    result = df.copy()
    for feature_name in df.columns:
        max_value = df[feature_name].max()
        min_value = df[feature_name].min()
        result[feature_name] = (df[feature_name] - min_value) / (max_value - min_value)
    return result

# z-score normalization function
def z_score_normalize(df):
    result = df.copy()
    for feature_name in df.columns:
        mean_value = df[feature_name].mean()
        std_value = df[feature_name].std()
        result[feature_name] = (df[feature_name] - mean_value) / std_value
    return result

# log-scale normalization function
def log_scale_normalize(df):
    result = df.copy()
    for feature_name in df.columns:
        result[feature_name] = np.log(df[feature_name])
    return result

# decimal scaling normalization function
def decimal_scale_normalize(df):
    result = df.copy()
    for feature_name in df.columns:
        max_value = df[feature_name].max()
        j = 0
        while max_value > 1:
            max_value /= 10
            j += 1
        result[feature_name] = df[feature_name] / (10 ** j)
    return result

In [7]:
df.dtypes

dtype('float64')

In [10]:
# Select the desired columns
data_fornormal = df[['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term']]

# Apply the minmaxx function
minmax_norm_data = minmaxx(data_fornormal)
minmax_norm_data

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term
0           0.070489           0.000000         NaN          0.743590
1           0.054830           0.036192    0.172214          0.743590
2           0.035250           0.000000    0.082489          0.743590
3           0.030093           0.056592    0.160637          0.743590
4           0.072356           0.000000    0.191027          0.743590
..               ...                ...         ...               ...
609         0.034014           0.000000    0.089725          0.743590
610         0.048930           0.000000    0.044863          0.358974
611         0.097984           0.005760    0.353111          0.743590
612         0.091936           0.000000    0.257598          0.743590
613         0.054830           0.000000    0.179450          0.743590

[614 rows x 4 columns]

In [11]:
# Apply Z_score_norm
z_scorenorm = z_score_normalize(data_fornormal)
z_scorenorm

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term
0           0.072931          -0.554036         NaN          0.276411
1          -0.134302          -0.038700   -0.215127          0.276411
2          -0.393427          -0.554036   -0.939534          0.276411
3          -0.461686           0.251774   -0.308599          0.276411
4           0.097649          -0.554036   -0.063236          0.276411
..               ...                ...         ...               ...
609        -0.409796          -0.554036   -0.881114          0.276411
610        -0.212383          -0.554036   -1.243317         -2.487699
611         0.436818          -0.472019    1.245369          0.276411
612         0.356773          -0.554036    0.474227          0.276411
613        -0.134302          -0.554036   -0.156707          0.276411

[614 rows x 4 columns]

In [12]:
# Apply Logscale
log_scalenorm = log_scale_normalize(data_fornormal)
log_scalenorm

/usr/local/lib/python3.9/dist-packages/pandas/core/arraylike.py:397: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term
0           8.674026               -inf         NaN          5.886104
1           8.430109           7.318540    4.852030          5.886104
2           8.006368               -inf    4.189655          5.886104
3           7.856707           7.765569    4.787492          5.886104
4           8.699515               -inf    4.948760          5.886104
..               ...                ...         ...               ...
609         7.972466               -inf    4.262680          5.886104
610         8.320205               -inf    3.688879          5.192957
611         8.996157           5.480639    5.533389          5.886104
612         8.933664               -inf    5.231109          5.886104
613         8.430109               -inf    4.890349          5.886104

[614 rows x 4 columns]

In [13]:
# Apply decimal Sclae
decimal_norm = decimal_scale_normalize(data_fornormal)
decimal_norm

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term
0            0.05849            0.00000         NaN              0.36
1            0.04583            0.01508       0.128              0.36
2            0.03000            0.00000       0.066              0.36
3            0.02583            0.02358       0.120              0.36
4            0.06000            0.00000       0.141              0.36
..               ...                ...         ...               ...
609          0.02900            0.00000       0.071              0.36
610          0.04106            0.00000       0.040              0.18
611          0.08072            0.00240       0.253              0.36
612          0.07583            0.00000       0.187              0.36
613          0.04583            0.00000       0.133              0.36

[614 rows x 4 columns]

In [14]:
# Functions for Standardization
# mean_standardization function
def mean_standardize(df):
    result = df.copy()
    for feature_name in df.columns:
        mean_value = df[feature_name].mean()
        max_value = df[feature_name].max()
        min_value = df[feature_name].min()
        result[feature_name] = (df[feature_name] - mean_value) / (max_value - min_value)
    return result

# scaling to unit length function
def scale_to_unit_length(df):
    result = df.copy()
    for feature_name in df.columns:
        norm_value = np.linalg.norm(df[feature_name])
        result[feature_name] = df[feature_name] / norm_value
    return result

In [15]:
data_scale = df[['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term']]

# Apply Mean_standard
mean_stand = mean_standardize(data_scale)
mean_stand

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term
0           0.005511          -0.038910         NaN          0.038462
1          -0.010148          -0.002718   -0.026646          0.038462
2          -0.029727          -0.038910   -0.116371          0.038462
3          -0.034885           0.017682   -0.038223          0.038462
4           0.007378          -0.038910   -0.007832          0.038462
..               ...                ...         ...               ...
609        -0.030964          -0.038910   -0.109135          0.038462
610        -0.016048          -0.038910   -0.153997         -0.346154
611         0.033006          -0.033150    0.154252          0.038462
612         0.026958          -0.038910    0.058738          0.038462
613        -0.010148          -0.038910   -0.019410          0.038462

[614 rows x 4 columns]

In [16]:
# Apply Scale to unit
mean_stu = scale_to_unit_length(data_scale)
mean_stu

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term
0           0.028955           0.000000         NaN               NaN
1           0.022688           0.018203         NaN               NaN
2           0.014851           0.000000         NaN               NaN
3           0.012787           0.028464         NaN               NaN
4           0.029703           0.000000         NaN               NaN
..               ...                ...         ...               ...
609         0.014356           0.000000         NaN               NaN
610         0.020327           0.000000         NaN               NaN
611         0.039960           0.002897         NaN               NaN
612         0.037539           0.000000         NaN               NaN
613         0.022688           0.000000         NaN               NaN

[614 rows x 4 columns]

In [17]:
# Using Library
from sklearn.preprocessing import StandardScaler, FunctionTransformer
# Z-score normalization (standardization) using StandardScaler
scaler = StandardScaler()
z_score_normalized_data = scaler.fit_transform(data_scale)
print('Z-score normalized data:')
print(z_score_normalized_data)



Z-score normalized data:
[[ 0.07299082 -0.55448733         nan  0.27664167]
 [-0.13441195 -0.03873155 -0.21530913  0.27664167]
 [-0.39374734 -0.55448733 -0.94032807  0.27664167]
 ...
 [ 0.43717437 -0.47240418  1.24642259  0.27664167]
 [ 0.35706382 -0.55448733  0.47462824  0.27664167]
 [-0.13441195 -0.55448733 -0.15683986  0.27664167]]


In [18]:
# Log scaling using FunctionTransformer
transformer = FunctionTransformer(np.log1p)
log_scaled_data = transformer.transform(data_scale)
print('Log scaled data:')
print(log_scaled_data)

Log scaled data:
     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term
0           8.674197           0.000000         NaN          5.888878
1           8.430327           7.319202    4.859812          5.888878
2           8.006701           0.000000    4.204693          5.888878
3           7.857094           7.765993    4.795791          5.888878
4           8.699681           0.000000    4.955827          5.888878
..               ...                ...         ...               ...
609         7.972811           0.000000    4.276666          5.888878
610         8.320448           0.000000    3.713572          5.198497
611         8.996280           5.484797    5.537334          5.888878
612         8.933796           0.000000    5.236442          5.888878
613         8.430327           0.000000    4.897840          5.888878

[614 rows x 4 columns]
